name: 'Get Vercel Deployment Url'
description: 'Get the latest deployment url for a specific commit'
author: 'Tanner B. Hess Webber'
inputs:
  commit_hash:
    required: false
    description: 'The commit hash for which the deployment URL should be extracted'
    default: ${{ github.sha }}
  vercel_access_token:
    required: true
    description: 'The Vercel access token to use for authentication'
  vercel_team_id:
    required: false
    description: 'The Vercel team id to use as the context for the request'
  vercel_project_id:
    required: false
    description: 'The Vercel project id to use to narrow the scope'
runs:
  using: 'node16'
  main: 'dist/index.js'
